DM-31193: Add note about detectors 2,61 to readme
lsst/ap_verify_hits2015 pull request #29
Opened 2021-10-12 02:35 UTC by parejkoj

2021-10-12 18:25 UTC, kfindeisen requested changes
I don't think the data are actually missing; can you check what goes wrong if you try to process these detectors?

2021-10-12 18:25 UTC, kfindeisen commented on README.md
> +Due to problems with detectors 2 and 61, this repository does not contain any data or calibrations for those detectors. Because of this, you must specify this data-query argument when running ap_veri
Can you double-check this? `butler query-datasets`, at least, thinks there are both raws and calibs with these detectors.

2021-10-13 20:41 UTC, parejkoj commented on README.md
> +Due to problems with detectors 2 and 61, this repository does not contain any data or calibrations for those detectors. Because of this, you must specify this data-query argument when running ap_veri
That's what this thread was about:

https://lsstc.slack.com/archives/C2B6X08LS/p1633655323064500

If I don't skip them, the task won't even start.

2021-10-18 21:51 UTC, kfindeisen commented on README.md
> +Due to problems with detectors 2 and 61, this repository does not contain all the necessary data to process these detectors.
I'm not convinced the data are really missing, rather than e.g. corrupted. Maybe:
```suggestion
Due to problems with detectors 2 and 61, this repository cannot process these detectors.
```

2021-10-19 17:28 UTC, kfindeisen approved these changes

2021-10-19 17:45 UTC, merged